Algoritmo "contando..."
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Autor(a)    : Maria Eduarda
// Data atual  : 11/2022
Var
num: vetor [0..9] de inteiro
cont,soma: inteiro


Inicio

para cont de 0 ate 9 faca
 escreval ("Digite um numero")
          leia(num[cont])

 soma <- soma + (num[cont])
fimpara

escreval("A soma é: ",soma)



Fimalgoritmo